~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1296.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1297.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1298.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1299.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1300.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1301.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1302.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1308.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1309.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1310.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1311.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1312.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1313.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1314.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1320.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1321.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1322.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1323.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1324.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1325.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1326.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1332.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1333.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1334.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1335.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1336.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1337.xml $1&
~/TriDAS_r59/pixel/PixelAnalysisTools/test/bin/linux/x86_64_centos7/PixelAnalysis.exe ~/TriDAS_r59/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_1338.xml $1&
